
volumes:
  jenkins-data:

networks:
  backend: 

services:
  jenkins:
    user: root
    privileged: true 
    image: yourusername/jenkins
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock